"""add category_id and product_id fields

Revision ID: f02f9c98a7a8
Revises: a0b674cf45fe
Create Date: 2025-10-27 18:35:26.131239+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f02f9c98a7a8'
down_revision = 'a0b674cf45fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
